name: PUL-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SLN_FILE: PartsUnlimited.sln
  PACKAGE_TEMP_PATH: Content\D_C\a\PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\obj\Release\Package\PackageTmp
  WEB_APP_NAME: pulweb
  
jobs:
  build:
    name: PUL Build Job using VS2019
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: NuGet restore
        run: nuget restore
        
      - name: BuildApp
        run: |
          msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{github.workspace}}\stagingdir"
     
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{github.workspace}}\stagingdir
